### ISSUE TITLE
Error: hashes must be at least 20 bytes long

### ISSUE THREAD

**Issue by SionoiS** [KenCloud-Tech/go-ipld-prolly-trees#8]
I'm trying to import the .car fixtures in IPFS but i get this error. 
```Error: hashes must be at least 20 bytes long```
IPFS v0.19.1

**Comment by sssion** [comment]
Hi, can you give more detail about the case? I mean where you met `Error: hashes must be at least 20 bytes long` ?   Some IPFS command action about the the car file ?

**Comment by SionoiS** [comment]
I downloaded the .car in the fixture folder and used ```ipfs dag import tree.car```

**Comment by sssion** [comment]
OK, I commit and resolve the problem.  It's caused by the DefaultLinkProto, I set the MhLength as 16, and is smaller than the ipfs dag import smallest length
